
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  int FUNCTION = 2;
  int GE = 34;
  int UMINUS = 42;
  int SLPAR = 22;
  int SEMI = 25;
  int INT = 49;
  int MINUS = 39;
  int FOR = 10;
  int BRPAR = 21;
  int WRITE = 14;
  int NOT = 16;
  int AND = 27;
  int LT = 29;
  int RPAR = 19;
  int NIL = 53;
  int NOP = 37;
  int OR = 28;
  int BOOL = 50;
  int COMMA = 24;
  int DIV = 41;
  int FLOAT_CONST = 45;
  int PLUS = 38;
  int ASSIGN = 36;
  int MAIN = 3;
  int IF = 5;
  int ID = 43;
  int LE = 30;
  int EOF = 0;
  int RETURN = 15;
  int TRUE = 47;
  int INT_CONST = 44;
  int error = 1;
  int GLOBAL = 12;
  int SRPAR = 23;
  int EQ = 31;
  int TIMES = 40;
  int ARROW = 35;
  int COLON = 26;
  int ELSE = 7;
  int SHARP = 17;
  int READ = 13;
  int WHILE = 8;
  int FLOAT = 51;
  int BLPAR = 20;
  int THEN = 6;
  int NE = 32;
  int END = 4;
  int STRING = 52;
  int LPAR = 18;
  int LOCAL = 11;
  int FALSE = 48;
  int STRING_CONST = 46;
  int GT = 33;
  int DO = 9;
  String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "MAIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "LOCAL",
  "GLOBAL",
  "READ",
  "WRITE",
  "RETURN",
  "NOT",
  "SHARP",
  "LPAR",
  "RPAR",
  "BLPAR",
  "BRPAR",
  "SLPAR",
  "SRPAR",
  "COMMA",
  "SEMI",
  "COLON",
  "AND",
  "OR",
  "LT",
  "LE",
  "EQ",
  "NE",
  "GT",
  "GE",
  "ARROW",
  "ASSIGN",
  "NOP",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE",
  "INT",
  "BOOL",
  "FLOAT",
  "STRING",
  "NIL"
  };
}

